- name: download,  install,  start and enable nginx
  hosts: web
  become: yes
  tasks:
  - name: download and install nginx
    ansible.builtin.pacakage:
      name: nginx
      state: latest
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
