- name: vars via vars file
  hosts: web
  vars_files:
    - vars.yaml
  tasks:
  - name: print vars from vars_files
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from {{trainer}}, duration: {{duration}}."
