- name: vars via vars_file
  hosts: web
  vars_files:
    - vars.yaml
  tasks:
    name: print vars from vars_files
    ansible.builting.debug:
      msg: "Hi, we are learning {{course}} from {{trainer}}, duration: {{duration}}."
