- name: org preferences test
  hosts: web
  # vars:
  #   WISHES: "good morning from play variables"
  vars_files:
    - vars.yaml
  # vars_prompt:
  #   - name: WISHES
  #     prompt: "please enter wishes"
  #     private: false
  tasks:
    - name: check preferences
      # vars: 
      #   WISHES: "good morning from task variables"
      ansible.builtin.debug:
        msg: "Hello, good {{WISHES}}"

#1. arguments
#2. task
#3. file
#4. prompt
#5. play
#6. inventory
#7. role 
