- name: different types of filters
  hosts: localhost
  tasks:
    - name: print default values
      ansible.builtin.debug:
        msg: "{{course | default ('ansible')}}"

- name: upper case
  hosts: localhost
  vars: 
    greeting: "hello, good morning"
  tasks: 
  - name: convert into upper case
    ansible.builtin.debug: 
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD MORNING"
  tasks: 
  - name: convert  into lowercase
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars: 
    numbers: [1, 1,2,3,3,4,5,5]
  tasks:
  - name: print unique numbers
    ansible.builtin.debug:
      msg: "numbers | unique"