- name: different types of filters
  hosts: localhost
  tasks:
    - name: print default values
      ansible.builtin.debug:
        msg: "{{course | default ('ansible')}}"

- name: upper case
  hosts: localhost
  vars: 
    greeting: "hello, good morning"
  tasks: 
  - name: convert into upper case
    ansible.builtin.debug: 
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD MORNING"
  tasks: 
  - name: convert  into lowercase
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars: 
    numbers: [1, 1,2,3,3,4,5,5]
  tasks:
  - name: print unique numbers
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

- name: print min and max ages
  hosts: localhost
  vars: 
    ages: [42,35, 35,10]
  tasks: 
  - name: print min and max ages
    ansible.builtin.debug:
      msg: "min age: {{ages | min}}, max age: {{ages | max}}"

- name: convert disct into list/items
  hosts: localhost
  vars:
    my_dict:
      sourse: DevOps
      trainer: siva kumar
      duration: 180 days
  tasks:
    - name: before convert
      ansible.builtin.debug:
        msg: "before converstion {{my_dict}}"
    - name: after conversion
      ansible.builtin.debug: 
        msg: "after conversion {{my_dict | dict2items}}
- name: convert item/list to dic
  hosts: localhost
  vars: 
    my_list:
    - {'key': 'course', 'value': 'Devops'}
    - {'key': 'trainer', 'value': 'siva kumar'}
    - {'key': 'duration', 'value': '150hrs'}
  task: 
  - name: before convert
    ansible.builtin.debug:
      msg: "before convert {{my_list}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert {{my_list | items2dict}}"