- name: different types of filters
  hosts: localhost
  tasks:
    - name: print default values
      ansible.builtin.debug:
        msg: "{{course | default ('ansible')}}"
- name: upper case
  hosts: localhost
  vars: 
    greeting: "hello, good morning"
  tasks: 
  - name: convert into upper case
    ansible.builtin.debug: 
      msg: "{{ greeting | upper }}""