- name: demo on loops
  hosts: localhost
  tasks:
    - name: print names from loops
      ansible.builtin.debug:
        msg: "hello {{item}}"
      loop:
        - linux
        - devops
        - aws
