- name: installng packages using loops
  hosts: localhost
  become: yes
  tasks:
    - name: install and uninsall using loops
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'mysql', state: 'absent' }
        - { name: 'nginx', state: 'latest' }
        - { name: 'postfix', state: 'absent'}
