- name: convert disct into list/items
  hosts: localhost
  vars:
    my_dict:
      sourse: DevOps
      trainer: siva kumar
      duration: 180 days
  tasks:
    - name: before convert
      ansible.builtin.debug:
        msg: "before converstion {{my_dict}}"
    - name: after conversion
      ansible.builtin.debug: 
        msg: "after conversion {{my_dict | dict2items}}
